using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Timers;

namespace TimerExample
{
    class Program
    {
        static void Main(string[] args)
        {

            Timer myTimer = new Timer(2000); // a timer that runs every 2 seconds

            myTimer.Elapsed += myTimer_Elapsed; // myTimer raises an event called Elapsed - we want to create a handler (method) that runs whenevre this event is raised - this is caleld an event handler
            myTimer.Elapsed += myTimer_Elapsed2; // 2nd event handler raised

            myTimer.Start();

            Console.WriteLine("Press enter to remove the red event...");
            Console.ReadLine();

            // allow user to remove the 2nd timer from the app
            myTimer.Elapsed -= myTimer_Elapsed2;
            Console.ReadLine();

        }

        // The MyTimer_Elapsed method stub below was created autmatically by typing the name of the event above in the code: "myTimer.Elapsed"
        // then the addition operator "+=" and hitting tab as directed - this is a function of Visual Studio editor and is very useful tool
        static void myTimer_Elapsed(object sender, ElapsedEventArgs e) // event handler code
        {
            Console.ForegroundColor = ConsoleColor.White;
            Console.WriteLine(e.SignalTime);
            // Console.WriteLine("Elapsed: {0:HH:mm:ss.ffff}", e.SignalTime);

            // throw new NotImplementedException(); // autogenerated throw call
        }

        // 2nd method (event handler) that corresponds to the 2nd event raising code above that calls myTimer_Elapsed2 method
        static void myTimer_Elapsed2(object sender, ElapsedEventArgs e)
        {
            Console.ForegroundColor = ConsoleColor.DarkRed;
            Console.WriteLine(e.SignalTime);
            // Console.WriteLine("Elapsed: {0:HH:mm:ss.ffff}", e.SignalTime);
        }

    }

}
